# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# calculate_GWR.py
# Created on: 2022-04-21 13:54:22.00000
#   (generated by JCT)
# Description: 对OLR\GWR\GTWR的结果进行十折的分类，同时按照折计算相关统计参数
# PS：前提是要在文件下面建立1-10的文件夹，可以makedirs，这里没写
# ---------------------------------------------------------------------------
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import xlrd
import csv
import pandas as pd
import numpy as np

def gwr_split(file_path_gen, model_name):
    file_path = file_path_gen + model_name + "/" + model_name + ".xls"
    book = xlrd.open_workbook(file_path)
    sheet = book.sheets()[0]
    nrows = sheet.nrows
    fold = 247 #一折是247
    for index in range(1, 11):
        list_train = []
        list_val = []
        list_test = []
        index1 = fold * (index - 1) + 1
        index2 = index1 + fold
        for i in range(0, index1):
            row = sheet.row_values(i)
            list_train.append(row)
        for j in range(index1, index2):
            row = sheet.row_values(j)
            list_val.append(row)
        for k in range(index2, 2471):
            row = sheet.row_values(k)
            list_train.append(row)

        for l in range(2471, nrows):
            row = sheet.row_values(l)
            list_test.append(row)

        file_save_path = file_path_gen + model_name + "/" + str(index) + "/"
        csv_train = file_save_path + "train.csv"
        csv_val = file_save_path + "val.csv"
        csv_test = file_save_path + "test.csv"
        list = row = sheet.row_values(0)
        with open(csv_train, 'w', newline='') as f1:
            writer = csv.writer(f1)
            writer.writerows(list_train)
            f1.close()
        with open(csv_val, 'w', newline='') as f2:
            writer = csv.writer(f2)
            writer.writerow(list)
            writer.writerows(list_val)
            f2.close()
        with open(csv_test, 'w', newline='') as f3:
            writer = csv.writer(f3)
            writer.writerow(list)
            writer.writerows(list_test)
            f3.close()

def calculate(file_path_gen, model_name):
    list=[]
    for index in range(1,11):
        file_path_folder=file_path_gen+model_name+"/"+str(index)+"/"
        file_name=["train","val","test"]
        for name in file_name:
            file_path=file_path_folder+name+".csv"
            data=pd.read_csv(file_path)
            y_actual = data[['Observed']] # 这里和下一行要根据实际的名字进行修改
            y_predicted = data[['Predicted']]
            y_actual = np.array(y_actual, dtype='float')
            y_predicted = np.array(y_predicted, dtype='float')


            r2 = r2_score(y_actual, y_predicted)
            rmse = np.sqrt(mean_squared_error(y_actual, y_predicted))
            mae = mean_absolute_error(y_actual, y_predicted)
            mape = np.mean(np.abs((y_predicted - y_actual) / np.maximum(y_actual, 0.01)))
            pccs = np.corrcoef(np.transpose(y_actual), np.transpose(y_predicted))

            row=tuple((index,name,r2,rmse,mae,mape,pccs[0][1]))
            list.append(row)
    with open(file_path_gen+model_name+"/res.csv", 'w', newline='') as f:
        title =["index","type","r2","rmse","mae","mape","pccs"]
        writer = csv.writer(f)
        writer.writerow(title)
        writer.writerows(list)
        f.close()


if __name__ == '__main__':
    file_path_gen = "C:/Users/DELL/Desktop/model/gtwr/"
    model_name = "aag"
    gwr_split(file_path_gen, model_name)
    calculate(file_path_gen, model_name)
