# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# csv_merge.py
# Created on: 2022-04-08 13:31:27.00000
#   (generated by JCT)
# Description: 代码跑出预测的xls文件合成一个csv，以便后续处理
# ---------------------------------------------------------------------------
# python37
import csv
import xlrd
original_number =2907
year ="2016"
for index in range(5,13):
    month =str(index)
    model_label ="20220406070531"
    data_file_gen = "F:/result/"+year+"/"  # 预测的result的xls的文件夹
    model_name = "gtnnwr"
    save_file_path = "F:/result/"+year+"/"+month+"/res_merge"+model_label+".csv"  # 要存储的位置和文件名
    for i in range(75):  # 经过raster_input.py处理之后，128个栅格分块会被去除没有数据的分块，剩下的为75块，即有75个csv
        data_file_path = data_file_gen + month + "/test_" + str(i) + "/" + model_name + "/test_" + str(
            i) + "_10_cv10_"+model_label+"_restore.xls"
        wb = xlrd.open_workbook_xls(data_file_path)
        sheet = wb.sheet_by_name("data")
        len_row = sheet.nrows
        list1 = []
        for j in range(original_number+1, len_row):  # 2908是因为原训练验证测试数据为2907条
            row = (sheet.row_values(j, 3, 5)) + sheet.row_values(j, 22, 23)  # 3、4两列是经纬度，22列是预测的norm值
            list1.append(row)

        with open(save_file_path, 'a+', newline='') as f:
            writer = csv.writer(f)
            list=['lat','lon','result']
            writer.writerow(list)
            writer.writerows(list1)
            f.close()
    print(save_file_path+" is ok")

