# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_output.py
# Created on: 2022-04-11 17:31:21.00000
#   (generated by JCT)
# Description: 将csv转换成栅格
# ps: 要用python2.7+arcpy  或者 ArcGIS自带的python
# ---------------------------------------------------------------------------

# python27
# Import arcpy module
import arcpy


# Local variables:
year ="2017"
file_gen="F:\\result\\"+year
save_file="F:\\result\\"
model_label ="20220406070531"
for index in range(7,13):
    month=str(index)
    res_merge_csv = file_gen+"\\"+month+"\\res_merge"+model_label+".csv"
    view = "view"+month
    toPoint_shp = file_gen+"_"+month+"\\toPoint"+model_label+".shp"
    toPoint_shp__2_ = toPoint_shp
    toPoint_shp__3_ = toPoint_shp__2_
    toPoint_Project = file_gen+"_"+month+"\\toPoint_Project"+model_label+".shp"
    toPoint_Project_PointToRaste = file_gen+"_"+month+"\\result"+model_label+".tif"

    # Process: 创建 XY 事件图层
    arcpy.MakeXYEventLayer_management(res_merge_csv, "lon", "lat", view,
                                      "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision",
                                      "")
    print ( "MakeXYEventLayer"+ " is ok")

    # Process: 要素转点
    arcpy.FeatureToPoint_management(view, toPoint_shp, "CENTROID")
    print (toPoint_shp+" is ok")

    # Process: 添加字段
    arcpy.AddField_management(toPoint_shp, "NO3", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

    # Process: 计算字段 把计算得到的字段乘以10000，因为点转栅格只能为整形
    arcpy.CalculateField_management(toPoint_shp__2_, "NO3", "[result]*10000", "VB", "")
    print ("CalculateField" + " is ok")

    # Process: 投影
    arcpy.Project_management(toPoint_shp__3_, toPoint_Project,
                             "PROJCS['CGCS2000_3_Degree_GK_CM_120E',GEOGCS['GCS_China_Geodetic_Coordinate_System_2000',DATUM['D_China_2000',SPHEROID['CGCS2000',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Gauss_Kruger'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',120.0],PARAMETER['Scale_Factor',1.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]",
                             "",
                             "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]",
                             "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")
    print (toPoint_Project + " is ok")
    # Process: 点转栅格
    arcpy.PointToRaster_conversion(toPoint_Project, "NO3", toPoint_Project_PointToRaste, "MEAN", "NONE", "500")
    print (toPoint_Project_PointToRaste+" is ok")



