# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster_input.py
# Created on: 2022-04-06 20:23:36.00000
#   (generated by JCT)
# Description: 将切割好的栅格文件转成csv格式
# ps: 要用python3,特别是rasterio的包
# ---------------------------------------------------------------------------

# python36
import codecs
import rasterio
import csv
import numpy as np
import pandas as pd
year ="2016"
for index in range(1,13):
    month = str(index)
    rasters_save_path_gen = 'F:/result/'+year+'_' + month + '/clip16/'  # 存储raster的文件夹
    rasterName = year+"_" + month
    file_save_path_gen = 'C:/Users/DELL/Desktop/'+year+'/' + month + '/csv/'  # 存储csv的文件夹
    file_source_path = 'C:/Users/DELL/Desktop/pic/test.csv'  # 原数据 2907条数据，在这个基础上进行拼接

    file_num = 0
    for i in range(128):  # 128是分割成8*16

        file_save_path = file_save_path_gen + 'test_' + str(file_num) + ".csv"
        raster_save_path = rasters_save_path_gen + rasterName + str(i) + ".TIF"
        df = pd.read_csv(file_source_path)
        df.to_csv(file_save_path, index=0)  # 不保留index列

        f = codecs.open(file_save_path, 'a+', 'gbk')
        writer = csv.writer(f)
        bands = []

        with rasterio.open(raster_save_path) as ds:
            width = ds.width
            height = ds.height

            for i in range(1, 8):
                bands.append(ds.read(i))
            cell_num = 0
            for i in range(width):

                for j in range(height):
                    # 不这么分开写，好像写进csv会有问题
                    b1 = bands[0][j, i]
                    b2 = bands[1][j, i]
                    b3 = bands[2][j, i]
                    b4 = bands[3][j, i]
                    b5 = bands[4][j, i]
                    b6 = bands[5][j, i]
                    b7 = bands[6][j, i]

                    if np.isnan(b1) or np.isnan(b2) or np.isnan(b3) or np.isnan(b4) or np.isnan(b5) or np.isnan(
                            b6) or np.isnan(b7):
                        continue
                    b1 = b1 / 10000
                    b2 = b2 / 10000
                    b3 = b3 / 10000
                    b4 = b4 / 10000
                    b5 = b5 / 10000
                    b6 = b6 / 10000
                    b7 = b7 / 10000
                    x, y = ds.xy(j, i)
                    data = tuple(("sample",month, y, x, b1, b2, b3, b4, b5, b6, b7, "0.0"))
                    writer.writerow(data)
                    cell_num += 1

            if (cell_num != 0):
                file_num += 1
        f.close()
    print(rasterName+" is ok")

